# Generated by Django 2.0 on 2017-12-26 02:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.TextField()),
                ('date', models.DateField()),
                ('place', models.TextField()),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('num_person', models.PositiveIntegerField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('instruments', models.TextField(null=True)),
                ('focus', models.TextField(null=True)),
                ('vos', models.TextField(null=True)),
                ('result', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.TextField()),
                ('date', models.DateField()),
                ('place', models.TextField()),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('num_person', models.PositiveIntegerField()),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('instruments', models.TextField(null=True)),
                ('focus', models.TextField(null=True)),
                ('vos', models.TextField(null=True)),
                ('result', models.TextField(null=True)),
            ],
        ),
    ]
